services:
  skymoth:
    depends_on:
      db:
        condition: service_healthy
    build: .
    restart: always
    env_file: .env
    environment:
      - POSTGRES_HOST=db
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: postgres
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 60
    volumes:
      - /var/lib/skymoth/pgdata:/var/lib/postgresql/data